apiVersion: apps/v1
kind: Deployment
metadata:
  name: mishmash-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mishmash-operator
  template:
    metadata:
      labels:
        name: mishmash-operator
    spec:
      serviceAccountName: mishmash-operator
      containers:
        - name: mishmash-operator
          # Replace this with the built image name
          image: quay.io/kirils/mishmash-operator:v0.0.1
          command:
          - mishmash-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mishmash-operator"
